package com.example.scorecard.core.domain;

/**
 * The Enum UIEventType.
 */
public enum UIEventType {
	
	ADD_CLIENT,
	UPDATE_CLIENT,
	UPDATE_CLIENT_STATUS,
	REMOVE_CLIENT,
	
	ADD_GROUP,
	UPDATE_GROUP,
	REMOVE_GROUP,
	
	CLUSTER_MEMBER_STATUS,
	CLUSTER_MEMBERSHIP,
	CLUSTER_MEMBER_IDENTITY,
	CLUSTER_SERVICE_STATE,
	CLUSTER_CONFIGURATION,
	
	FAILOVER_SERVICE_STATE,
	
	ADD_TASK,
	UPDATE_TASK,
	REMOVE_TASK,
	
	UPDATE_CONFIGURATION_STATUS,
	
	ADD_RECENT_TASK,
	UPDATE_RECENT_TASK,
	BULK_UPDATE_RECENT_TASK,
	
	UPDATE_BACKUP_LIST,
	NEW_BACKUP,
	BACKUP_DELETED,
	
	CLIENT_LOG_DELETED,
	CLIENT_LOG_CREATED,
	
	DIRECTORY_CONNECTION_EXCEPTION,
	DIRECTORY_CONNECTION_STATUS,
	
	CITRIX_CONNECTION_STATUS,
	
	USER_LOGIN_SUCCESS

}
